### ISSUE TITLE
Failure to inspect ELF binaries

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#1121]
When scanning  https://repo1.maven.org/maven2/com/sun/jna/jna/3.0.9/jna-3.0.9.jar 
with `scan_single_package`, followed by `inspect_elf_binaries` inspect_elf_binaries fails with trace pasted below

We have two issues here:
- I do not know which file triggered the failure in the pipeline log so this is super hard to investigate. I would like this:
  - [x] #1122
- There is a failure and it should have been captured and not make the pipeline fail
  - [x] Keep on trucking if an inspected ELF binaries fails to be inspected

In ScanCode.io:
```
Unsupported relocation type: 22

Traceback:
  File "/opt/scancodeio/scanpipe/pipelines/__init__.py", line 191, in execute
    step(self)
  File "/opt/scancodeio/scanpipe/pipelines/inspect_elf_binaries.py", line 46, in collect_dwarf_source_path_references
    dwarf_paths = get_dwarf_paths(Path(self.project.codebase_path / elf.path))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scancodeio/venv/lib/python3.11/site-packages/elf_inspector/dwarf.py", line 41, in get_dwarf_paths
    for ptype, path in get_dwarf_cu_and_die_paths(location):
  File "/opt/scancodeio/venv/lib/python3.11/site-packages/elf_inspector/dwarf.py", line 74, in get_dwarf_cu_and_die_paths
    dwarfinfo = elffile.get_dwarf_info()
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scancodeio/venv/lib/python3.11/site-packages/elftools/elf/elffile.py", line 275, in get_dwarf_info
    dwarf_section = self._read_dwarf_section(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scancodeio/venv/lib/python3.11/site-packages/elftools/elf/elffile.py", line 801, in _read_dwarf_section
    reloc_handler.apply_section_relocations(
  File "/opt/scancodeio/venv/lib/python3.11/site-packages/elftools/elf/relocation.py", line 238, in apply_section_relocations
    self._do_apply_relocation(stream, reloc, symtab)
  File "/opt/scancodeio/venv/lib/python3.11/site-packages/elftools/elf/relocation.py", line 293, in _do_apply_relocation
    raise ELFRelocationError(

```

In bare ScanCode toolkit:
```
pip install scancode-toolkit elf-inspector
scancode --dwarf --yaml - --verbose com/sun/jna/ 
```
I get this:

```
Scanning done.
Some files failed to scan properly:
Path: jna/sunos-sparcv9/libjnidispatch.so
  ERROR: for scanner: dwarf-inspector:
  ERROR: Unknown error:
  Traceback (most recent call last):
    File "/tmp/foo/tmp/jna-3.0.9/venv/lib/python3.10/site-packages/scancode/interrupt.py", line 91, in interruptible
      return NO_ERROR, func(*(args or ()), **(kwargs or {}))
    File "/tmp/foo/tmp/jna-3.0.9/venv/lib/python3.10/site-packages/elf_inspector/plugin_dwarf.py", line 54, in get_dwarfs
      return dict(dwarf_source_paths=get_dwarf_paths(location))
    File "/tmp/foo/tmp/jna-3.0.9/venv/lib/python3.10/site-packages/elf_inspector/dwarf.py", line 41, in get_dwarf_paths
      for ptype, path in get_dwarf_cu_and_die_paths(location):
    File "/tmp/foo/tmp/jna-3.0.9/venv/lib/python3.10/site-packages/elf_inspector/dwarf.py", line 74, in get_dwarf_cu_and_die_paths
      dwarfinfo = elffile.get_dwarf_info()
    File "/tmp/foo/tmp/jna-3.0.9/venv/lib/python3.10/site-packages/elftools/elf/elffile.py", line 275, in get_dwarf_info
      dwarf_section = self._read_dwarf_section(
    File "/tmp/foo/tmp/jna-3.0.9/venv/lib/python3.10/site-packages/elftools/elf/elffile.py", line 801, in _read_dwarf_section
      reloc_handler.apply_section_relocations(
    File "/tmp/foo/tmp/jna-3.0.9/venv/lib/python3.10/site-packages/elftools/elf/relocation.py", line 238, in apply_section_relocations
      self._do_apply_relocation(stream, reloc, symtab)
    File "/tmp/foo/tmp/jna-3.0.9/venv/lib/python3.10/site-packages/elftools/elf/relocation.py", line 293, in _do_apply_relocation
      raise ELFRelocationError(
  elftools.common.exceptions.ELFRelocationError: Unsupported relocation type: 22
```

**Comment by tdruez** [comment]
@pombredanne implemented in https://github.com/nexB/scancode.io/pull/1123

From the changelog:

- Capture errors during the `inspect_elf_binaries` pipeline execution.
  Errors on resource inspection are stored as project error message instead of global
  pipeline failure.
  The problematic resource path is stored in the message details and displayed in the
  message list UI as a link to the resource details view.

![Screenshot 2024-03-19 at 17 24 43](https://github.com/nexB/scancode.io/assets/489057/442ea93f-6f20-4e5e-b509-0a2de36cc096)
