### ISSUE TITLE
Building wheel for psycopg2 (setup.py) ... error

### ISSUE THREAD

**Issue by vignesh-cloud-prog** [nexB/scancode.io#148]
I got this error while seeting up loally

``` 
Building wheels for collected packages: gunicorn, psycopg2, bitarray, click-didyoumean, ftfy, intbitset, patch, pefile, pyahocorasick, future, unicodecsv
  Building wheel for gunicorn (setup.py) ... done
  Created wheel for gunicorn: filename=gunicorn-20.1.0-py3-none-any.whl size=78917 sha256=8b01c067d32869221e6a9473316fe739f90e31ff7a9925f6c6d3900dc1e30ebb
  Stored in directory: /home/vighnesha/.cache/pip/wheels/21/4b/32/9be8daf8a4d73da26e4dba66c47c9b4b7d838a6b372981a3ed
  Building wheel for psycopg2 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/vighnesha/scancode.io/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-11m59sde/psycopg2_393f01fc94394416b2853b5db29340c3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-11m59sde/psycopg2_393f01fc94394416b2853b5db29340c3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-zw9hwn16
       cwd: /tmp/pip-install-11m59sde/psycopg2_393f01fc94394416b2853b5db29340c3/
  Complete output (36 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/psycopg2
  copying lib/compat.py -> build/lib.linux-x86_64-3.8/psycopg2
  copying lib/_lru_cache.py -> build/lib.linux-x86_64-3.8/psycopg2
  copying lib/errors.py -> build/lib.linux-x86_64-3.8/psycopg2
  copying lib/errorcodes.py -> build/lib.linux-x86_64-3.8/psycopg2
  copying lib/__init__.py -> build/lib.linux-x86_64-3.8/psycopg2
  copying lib/sql.py -> build/lib.linux-x86_64-3.8/psycopg2
  copying lib/_range.py -> build/lib.linux-x86_64-3.8/psycopg2
  copying lib/pool.py -> build/lib.linux-x86_64-3.8/psycopg2
  copying lib/extensions.py -> build/lib.linux-x86_64-3.8/psycopg2
  copying lib/_ipaddress.py -> build/lib.linux-x86_64-3.8/psycopg2
  copying lib/extras.py -> build/lib.linux-x86_64-3.8/psycopg2
  copying lib/_json.py -> build/lib.linux-x86_64-3.8/psycopg2
  copying lib/tz.py -> build/lib.linux-x86_64-3.8/psycopg2
  running build_ext
  building 'psycopg2._psycopg' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/psycopg
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPSYCOPG_VERSION=2.8.6 (dt dec pq3 ext lo64) -DPG_VERSION_NUM=130002 -DHAVE_LO64=1 -I/home/vighnesha/scancode.io/include -I/usr/include/python3.8 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-3.8/psycopg/psycopgmodule.o -Wdeclaration-after-statement
  unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
  
  It appears you are missing some prerequisite to build the package from source.
  
  You may install a binary package by installing 'psycopg2-binary' from PyPI.
  If you want to install psycopg2 from source, please install the packages
  required for the build and try again.
  
  For further information please check the 'doc/src/install.rst' file (also at
  <https://www.psycopg.org/docs/install.html>).
  
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for psycopg2
  Running setup.py clean for psycopg2
  Building wheel for bitarray (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/vighnesha/scancode.io/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-11m59sde/bitarray_6aa9720b89824ce3a571e54bc69f34e5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-11m59sde/bitarray_6aa9720b89824ce3a571e54bc69f34e5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-lmigr0fy
       cwd: /tmp/pip-install-11m59sde/bitarray_6aa9720b89824ce3a571e54bc69f34e5/
  Complete output (15 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/bitarray
  copying bitarray/__init__.py -> build/lib.linux-x86_64-3.8/bitarray
  copying bitarray/test_bitarray.py -> build/lib.linux-x86_64-3.8/bitarray
  running build_ext
  building 'bitarray._bitarray' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/bitarray
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/vighnesha/scancode.io/include -I/usr/include/python3.8 -c bitarray/_bitarray.c -o build/temp.linux-x86_64-3.8/bitarray/_bitarray.o
  unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for bitarray
  Running setup.py clean for bitarray
  Building wheel for click-didyoumean (setup.py) ... done
  Created wheel for click-didyoumean: filename=click_didyoumean-0.0.3-py3-none-any.whl size=2146 sha256=314c9cd3964d1c9f251b7267aa8c1e9e5c21396438515f4f38ba0d41399e0776
  Stored in directory: /home/vighnesha/.cache/pip/wheels/c2/97/1e/c7dda0b8e9616dcd8df2a2882e556ef62879967ac31e0e3d04
  Building wheel for ftfy (setup.py) ... done
  Created wheel for ftfy: filename=ftfy-4.4.3-py3-none-any.whl size=41068 sha256=48e4f248567878881ef4b105a1ce642172d2ccefcb973d5f4799de378c55aa7c
  Stored in directory: /home/vighnesha/.cache/pip/wheels/97/ea/83/0ea1632b87aa8a3ecdc2c3914d7dc786ed2ff37eb9e9242f3a
  Building wheel for intbitset (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/vighnesha/scancode.io/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-11m59sde/intbitset_7f7f25428a834955bf9d6ae4e6b1a759/setup.py'"'"'; __file__='"'"'/tmp/pip-install-11m59sde/intbitset_7f7f25428a834955bf9d6ae4e6b1a759/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-qamghrqo
       cwd: /tmp/pip-install-11m59sde/intbitset_7f7f25428a834955bf9d6ae4e6b1a759/
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  copying intbitset/intbitset_helper.py -> build/lib.linux-x86_64-3.8
  copying intbitset/intbitset_version.py -> build/lib.linux-x86_64-3.8
  running egg_info
  writing intbitset/intbitset.egg-info/PKG-INFO
  writing dependency_links to intbitset/intbitset.egg-info/dependency_links.txt
  writing requirements to intbitset/intbitset.egg-info/requires.txt
  writing top-level names to intbitset/intbitset.egg-info/top_level.txt
  warning: Failed to find the configured license file 'AUTHOR.rst'
  reading manifest file 'intbitset/intbitset.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.css' under directory 'docs/_themes'
  warning: no files found matching '*.css_t' under directory 'docs/_themes'
  warning: no files found matching '*.conf' under directory 'docs/_themes'
  warning: no files found matching '*.html' under directory 'docs/_themes'
  warning: no files found matching 'COPYING' under directory 'docs/_themes'
  warning: no files found matching 'README' under directory 'docs/_themes'
  warning: no files found matching '*.html' under directory 'docs/_templates'
  writing manifest file 'intbitset/intbitset.egg-info/SOURCES.txt'
  running build_ext
  building 'intbitset' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/intbitset
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/vighnesha/scancode.io/include -I/usr/include/python3.8 -c intbitset/intbitset.c -o build/temp.linux-x86_64-3.8/intbitset/intbitset.o -O3 -march=core2 -mtune=native
  unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for intbitset
  Running setup.py clean for intbitset
  Building wheel for patch (setup.py) ... done
  Created wheel for patch: filename=patch-1.16-py3-none-any.whl size=12407 sha256=f86ea395ec155261094834ac2e2b99d58a057e0363c11dadc44bacbcc0cad55f
  Stored in directory: /home/vighnesha/.cache/pip/wheels/ee/1f/d7/98669d171c98079d257b42489cd3781307dd4831bcbc8d840a
  Building wheel for pefile (setup.py) ... done
  Created wheel for pefile: filename=pefile-2019.4.18-py3-none-any.whl size=60822 sha256=98f6748a3f0c441119ad0ff71e38095c095153c33abd7b362615fe19cff1d936
  Stored in directory: /home/vighnesha/.cache/pip/wheels/42/52/d5/9550bbfb9eeceaf0f19db1cf651cc8ba41d3bcf8b4d20e4279
  Building wheel for pyahocorasick (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/vighnesha/scancode.io/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-11m59sde/pyahocorasick_a4f91c3b973f48d683670fc9642d6708/setup.py'"'"'; __file__='"'"'/tmp/pip-install-11m59sde/pyahocorasick_a4f91c3b973f48d683670fc9642d6708/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-md732t1x
       cwd: /tmp/pip-install-11m59sde/pyahocorasick_a4f91c3b973f48d683670fc9642d6708/
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'ahocorasick' extension
  creating build
  creating build/temp.linux-x86_64-3.8
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DAHOCORASICK_UNICODE= -I/home/vighnesha/scancode.io/include -I/usr/include/python3.8 -c pyahocorasick.c -o build/temp.linux-x86_64-3.8/pyahocorasick.o
  unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyahocorasick
  Running setup.py clean for pyahocorasick
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491059 sha256=d137227c891ddd527b9431d19e9490398261b3c2aaaffdf831b230b9ec9f720e
  Stored in directory: /home/vighnesha/.cache/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4
  Building wheel for unicodecsv (setup.py) ... done
  Created wheel for unicodecsv: filename=unicodecsv-0.14.1-py3-none-any.whl size=10767 sha256=05a009667827d710fa9ee012eb71c53bdea7cddc2143e874c0c0f03de1593335
  Stored in directory: /home/vighnesha/.cache/pip/wheels/35/dd/44/ccb37563a01457f5de74ccedccaee81b01a53e12addeab5e0f
Successfully built gunicorn click-didyoumean ftfy patch pefile future unicodecsv
Failed to build psycopg2 bitarray intbitset pyahocorasick
Installing collected packages: urllib3, soupsieve, six, PyYAML, pycparser, idna, chardet, certifi, text-unidecode, saneyaml, requests, intbitset, click, cffi, Beautifulsoup4, attrs, sortedcontainers, pluggy, cryptography, commoncode, plugincode, pdfminer.six, binaryornot, webencodings, typecode-libmagic, typecode, pyparsing, patch, isodate, banal, xmltodict, wcwidth, vine, tqdm, toml, regex, rdflib, publicsuffix2, ply, packaging, normality, more-itertools, MarkupSafe, lxml, joblib, html5lib, future, extractcode-libarchive, extractcode-7z, extractcode, boolean.py, urlpy, sqlparse, spdx-tools, pytz, pymaven-patch, pygments, pycryptodome, pyahocorasick, prompt-toolkit, pkginfo, pefile, packageurl-python, nltk, license-expression, jsonstreams, jinja2, javaproperties, jaraco.functools, gemfileparser, ftfy, fingerprints, fasteners, dparse2, debian-inspector, colorama, bitarray, asgiref, amqp, unicodecsv, scancode-toolkit, rpm-inspector-rpm, pyinstrument-cext, kombu, dockerfile-parse, Django, click-repl, click-plugins, click-didyoumean, billiard, XlsxWriter, redis, pyinstrument, psycopg2, gunicorn, djangorestframework, django-filter, django-environ, django-crispy-forms, container-inspector, celery, scancodeio
    Running setup.py install for intbitset ... error
    ERROR: Command errored out with exit status 1:
     command: /home/vighnesha/scancode.io/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-11m59sde/intbitset_7f7f25428a834955bf9d6ae4e6b1a759/setup.py'"'"'; __file__='"'"'/tmp/pip-install-11m59sde/intbitset_7f7f25428a834955bf9d6ae4e6b1a759/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-k3fi3yan/install-record.txt --single-version-externally-managed --compile --install-headers /home/vighnesha/scancode.io/include/site/python3.8/intbitset
         cwd: /tmp/pip-install-11m59sde/intbitset_7f7f25428a834955bf9d6ae4e6b1a759/
    Complete output (30 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    copying intbitset/intbitset_helper.py -> build/lib.linux-x86_64-3.8
    copying intbitset/intbitset_version.py -> build/lib.linux-x86_64-3.8
    running egg_info
    writing intbitset/intbitset.egg-info/PKG-INFO
    writing dependency_links to intbitset/intbitset.egg-info/dependency_links.txt
    writing requirements to intbitset/intbitset.egg-info/requires.txt
    writing top-level names to intbitset/intbitset.egg-info/top_level.txt
    warning: Failed to find the configured license file 'AUTHOR.rst'
    reading manifest file 'intbitset/intbitset.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.css' under directory 'docs/_themes'
    warning: no files found matching '*.css_t' under directory 'docs/_themes'
    warning: no files found matching '*.conf' under directory 'docs/_themes'
    warning: no files found matching '*.html' under directory 'docs/_themes'
    warning: no files found matching 'COPYING' under directory 'docs/_themes'
    warning: no files found matching 'README' under directory 'docs/_themes'
    warning: no files found matching '*.html' under directory 'docs/_templates'
    writing manifest file 'intbitset/intbitset.egg-info/SOURCES.txt'
    running build_ext
    building 'intbitset' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/intbitset
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/vighnesha/scancode.io/include -I/usr/include/python3.8 -c intbitset/intbitset.c -o build/temp.linux-x86_64-3.8/intbitset/intbitset.o -O3 -march=core2 -mtune=native
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/vighnesha/scancode.io/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-11m59sde/intbitset_7f7f25428a834955bf9d6ae4e6b1a759/setup.py'"'"'; __file__='"'"'/tmp/pip-install-11m59sde/intbitset_7f7f25428a834955bf9d6ae4e6b1a759/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-k3fi3yan/install-record.txt --single-version-externally-managed --compile --install-headers /home/vighnesha/scancode.io/include/site/python3.8/intbitset Check the logs for full command output.
make: *** [Makefile:50: conf] Error 1

```

I was run the command  `make dev` in venv

**Comment by tdruez** [comment]
HI @vignesh-cloud-prog it seems that you are missing some system packages required for building the dependencies. Could you try the following and re-run the `make dev` command?
```
sudo apt-get install build-essential libssl-dev python3-dev bzip2 xz-utils zlib1g libxml2-dev libxslt1-dev libpopt0
```

**Comment by vignesh-cloud-prog** [comment]
@tdruez  Thank you `make dev` command succesfully completed.
To install **psycopg2** on **Ubuntu** we should run `sudo apt-get install libpq-dev` and then `pip3 install Psycopg2`  then everything is fine.

**Comment by tdruez** [comment]
@vignesh-cloud-prog thanks for the report.

From https://scancodeio.readthedocs.io/en/latest/installation.html#pre-requisite

> On Linux, several OS packages are required by ScanCode toolkit. Make sure those are installed before attempting the ScanCode.io installation. Refer to ScanCode-toolkit Prerequisites

So make sure to install those as well https://scancode-toolkit.readthedocs.io/en/latest/getting-started/install.html#prerequisites

I will add a note on `libpq-dev` in the scancodeio docs.

**Comment by vignesh-cloud-prog** [comment]
having trouble with  `make postgres` command

```(env) vighnesha@vighnesha-VirtualBox:~/scancode.io$ make postgres
-> Configure PostgreSQL database
-> Create database user 'scancodeio'
sudo -u postgres createuser --no-createrole --no-superuser --login --inherit --createdb scancodeio || true
sudo -u postgres psql -c "alter user scancodeio with encrypted password 'scancodeio';" || true
ALTER ROLE
-> Drop 'scancodeio' database
sudo -u postgres dropdb scancodeio || true
dropdb: error: database removal failed: ERROR:  database "scancodeio" does not exist
-> Create 'scancodeio' database
sudo -u postgres createdb --encoding=utf-8 --owner=scancodeio scancodeio
make[1]: Entering directory '/home/vighnesha/scancode.io'
-> Apply database migrations
bin/python manage.py migrate
/home/vighnesha/scancode.io/lib/python3.8/site-packages/environ/environ.py:637: UserWarning: Error reading /home/vighnesha/scancode.io/.env - if you're not configuring your environment separately, check this.
  warnings.warn(
Traceback (most recent call last):
  File "/home/vighnesha/scancode.io/lib/python3.8/site-packages/environ/environ.py", line 273, in get_value
    value = self.ENVIRON[var]
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'SECRET_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 4, in <module>
    from scancodeio import command_line
  File "/home/vighnesha/scancode.io/scancodeio/__init__.py", line 52, in <module>
    WORKSPACE_LOCATION = get_workspace_location()
  File "/home/vighnesha/scancode.io/scancodeio/__init__.py", line 45, in get_workspace_location
    getattr(settings, "SCANCODEIO_WORKSPACE_LOCATION", None)
  File "/home/vighnesha/scancode.io/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/vighnesha/scancode.io/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/vighnesha/scancode.io/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/vighnesha/scancode.io/scancodeio/settings/__init__.py", line 23, in <module>
    from scancodeio.settings.dev import *
  File "/home/vighnesha/scancode.io/scancodeio/settings/dev.py", line 28, in <module>
    exec(parent_config.read())
  File "<string>", line 40, in <module>
  File "/home/vighnesha/scancode.io/lib/python3.8/site-packages/environ/environ.py", line 134, in str
    value = self.get_value(var, default=default)
  File "/home/vighnesha/scancode.io/lib/python3.8/site-packages/environ/environ.py", line 277, in get_value
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: Set the SECRET_KEY environment variable
make[1]: *** [Makefile:92: migrate] Error 1
make[1]: Leaving directory '/home/vighnesha/scancode.io'
make: *** [Makefile:103: postgres] Error 2
```
