### ISSUE TITLE
Failure: "Bad arguments: all arguments must be an Expression"

### ISSUE THREAD

**Issue by tdruez** [nexB/scancode.io#219]
Run log:
```
2021-06-18 07:26:24.72 Pipeline [root_filesystems] starting
2021-06-18 07:26:24.72 Step [extract_input_files_to_codebase_directory] starting
2021-06-18 07:40:00.16 Step [extract_input_files_to_codebase_directory] completed in 815.44 seconds
2021-06-18 07:40:00.17 Step [find_root_filesystems] starting
2021-06-18 07:40:00.17 Step [find_root_filesystems] completed in 0.00 seconds
2021-06-18 07:40:00.18 Step [collect_rootfs_information] starting
2021-06-18 07:40:00.18 Step [collect_rootfs_information] completed in 0.00 seconds
2021-06-18 07:40:00.18 Step [collect_and_create_codebase_resources] starting
2021-06-18 07:51:16.12 Step [collect_and_create_codebase_resources] completed in 675.93 seconds
2021-06-18 07:51:16.12 Step [collect_and_create_system_packages] starting
2021-06-18 07:53:16.59 Pipeline failed
```

Task output:
```
Bad arguments: all arguments must be an Expression: (LicenseSymbol('postgresql', is_exception=False), LicenseSymbol('henry-spencer-1999', is_exception=False), LicenseSymbol('tcl', is_exception=False), LicenseSymbol('other-permissive', is_exception=False), LicenseSymbol('bsd-new', is_exception=False), LicenseSymbol('other-permissive', is_exception=False), AND(OR(LicenseSymbol('artistic-perl-1.0', is_exception=False), LicenseSymbol('gpl-1.0-plus', is_exception=False)), LicenseSymbol('postgresql', is_exception=False), OR(LicenseSymbol('artistic-perl-1.0', is_exception=False), LicenseSymbol('gpl-1.0-plus', is_exception=False)), LicenseSymbol('gpl-1.0', is_exception=False)), LicenseSymbol('postgresql', is_exception=False), LicenseSymbol('mit', is_exception=False), LicenseSymbol('bsd-new', is_exception=False), LicenseSymbol('bsd-simplified', is_exception=False), LicenseSymbol('mit', is_exception=False), LicenseSymbol('other-permissive', is_exception=False), None, None, None)

Traceback:
  File "scancodeio/scanpipe/pipelines/__init__.py", line 96, in execute
    step(self)
  File "scancodeio/scanpipe/pipelines/root_filesystems.py", line 83, in collect_and_create_system_packages
    rootfs.scan_rootfs_for_system_packages(self.project, rfs)
  File "scancodeio/scanpipe/pipes/rootfs.py", line 212, in scan_rootfs_for_system_packages
    for i, (purl, package) in enumerate(installed_packages):
  File "scancodeio/scanpipe/pipes/debian.py", line 34, in package_getter
    for package in packages:
  File "python3.9/site-packages/packagedcode/debian.py", line 185, in get_installed_packages
    package.license_expression = dc.get_license_expression(
  File "python3.9/site-packages/packagedcode/debian_copyright.py", line 295, in get_license_expression
    return str(combine_expressions(expressions, unique=False))
  File "python3.9/site-packages/packagedcode/utils.py", line 175, in combine_expressions
    return str(relationship(*expressions))
  File "python3.9/site-packages/license_expression/__init__.py", line 1199, in __init__
    super(AND, self).__init__(*args)
  File "python3.9/site-packages/boolean/boolean.py", line 1468, in __init__
    super(AND, self).__init__(arg1, arg2, *args)
  File "python3.9/site-packages/boolean/boolean.py", line 1134, in __init__
    super(DualBase, self).__init__(arg1, arg2, *args)
  File "python3.9/site-packages/boolean/boolean.py", line 945, in __init__
    assert all(isinstance(arg, Expression) for arg in args), \
```

**Comment by tdruez** [comment]
The debian_copyright license detection can return `None` for license_expression_object
https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/debian_copyright.py#L291

Those are then pass on the `combine_expressions` that do not handle `None` as value.

```
from packagedcode.utils import combine_expressions
combine_expressions([None, 'zlib'])


Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Volumes/nexB/repos/scancode.io/lib/python3.9/site-packages/packagedcode/utils.py", line 176, in combine_expressions
    return str(relationship(*expressions))
  File "/Volumes/nexB/repos/scancode.io/lib/python3.9/site-packages/license_expression/__init__.py", line 1579, in __init__
    super(AND, self).__init__(*args)
  File "/Volumes/nexB/repos/scancode.io/lib/python3.9/site-packages/boolean/boolean.py", line 1468, in __init__
    super(AND, self).__init__(arg1, arg2, *args)
  File "/Volumes/nexB/repos/scancode.io/lib/python3.9/site-packages/boolean/boolean.py", line 1134, in __init__
    super(DualBase, self).__init__(arg1, arg2, *args)
  File "/Volumes/nexB/repos/scancode.io/lib/python3.9/site-packages/boolean/boolean.py", line 945, in __init__
    assert all(isinstance(arg, Expression) for arg in args), \
AssertionError: Bad arguments: all arguments must be an Expression: (None, LicenseSymbol('zlib', is_exception=False))
```

**Comment by tdruez** [comment]
My guess is that we should not include item for which the `license_detection.license_expression_object` is `None` https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/debian_copyright.py#L290

@pombredanne what's your take on this?

**Comment by AyanSinhaMahapatra** [comment]
@tdruez I've added a quick fix [here](https://github.com/nexB/scancode-toolkit/pull/2558/commits/8b050bc4d184452d5ff25cf712786ca470e7c45e), this should have been there.

I'm also looking more into what caused the `license_detection.license_expression_object` to be `None`, it seems to me that here: https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/debian_copyright.py#L589 if the `DebianLicensing.substitutions` doesn't have a key-value pair with the `debian_expression` key, which is something I should have added as a case and some related processing for that. I'm adding a fix for this too.

**Comment by tdruez** [comment]
@AyanSinhaMahapatra thanks for the fix.
Here's the file that caused the issue on my side, if you want to add a unit test and investigate more:
```
/usr/share/doc/zlib1g/copyright
```

```
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
Files-Excluded:
 contrib/ada
 contrib/amd64
 contrib/asm686
 contrib/blast
 contrib/delphi
 contrib/dotzlib
 contrib/gcc_gvmat64
 contrib/infback9
 contrib/inflate86
 contrib/iostream
 contrib/iostream2
 contrib/iostream3
 contrib/masmx64
 contrib/masmx86
 contrib/pascal
 contrib/puff
 contrib/testzlib
 contrib/untgz
 contrib/vstudio
 doc/rfc*

This is the pre-packaged Debian Linux version of the zlib compression
library.  It was packaged by Michael Alan Dorman <mdorman@debian.org>
from sources originally retrieved from ftp.uu.net in the directory
/pub/archiving/zip/zlib as the file zlib-1.0.4.tar.gz.

There is a homepage at http://www.gzip.org/zlib/ 

Acknowledgments:

  The deflate format used by zlib was defined by Phil Katz. The deflate
  and zlib specifications were written by Peter Deutsch. Thanks to all the
  people who reported problems and suggested various improvements in zlib;
  they are too numerous to cite here.

Copyright notice:

  Copyright (C) 1995-1998 Jean-loup Gailly and Mark Adler

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.

  Jean-loup Gailly        Mark Adler
  jloup@gzip.org          madler@alumni.caltech.edu
```

**Comment by AyanSinhaMahapatra** [comment]
Thanks++ for the file, I see the issue caused more clearly now, I'll add the fix I discussed above and add this as a unit test.

**Comment by tdruez** [comment]
@AyanSinhaMahapatra thanks for your input. Closing :)
