### ISSUE TITLE
scancode-toolkit update breaks Docker pipelines

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode.io#438]
Several package related functions used by the docker pipeline have been removed in the latest version of scancode-toolkit. Debian-related package handling, especially code that deals with handling the status files and such, work slightly differently than the way it used to. Functions that the pipelines relied on, like `get_installed_packages`, have been removed.

**Comment by JonoYang** [comment]
I brought in the code for `get_installed_packages` and its helper functions from a previous version of scancode and put it in `scanpipe/pipes/debian.py`, but there seems to be a problem with some part of license detection when I run the docker pipeline on `docker://ubuntu`:
```
'AND' object has no attribute 'iscanonical'

Traceback:
  File "/home/jono/nexb/src/scancode.io/scanpipe/pipelines/__init__.py", line 115, in execute
    step(self)
  File "/home/jono/nexb/src/scancode.io/scanpipe/pipelines/docker.py", line 93, in collect_and_create_system_packages
    docker.scan_image_for_system_packages(self.project, image)
  File "/home/jono/nexb/src/scancode.io/scanpipe/pipes/docker.py", line 166, in scan_image_for_system_packages
    for i, (purl, package, layer) in enumerate(installed_packages):
  File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/container_inspector/image.py", line 446, in get_installed_packages
    for purl, package in layer.get_installed_packages(packages_getter):
  File "/home/jono/nexb/src/scancode.io/scanpipe/pipes/debian.py", line 76, in package_getter
    for package in packages:
  File "/home/jono/nexb/src/scancode.io/scanpipe/pipes/debian.py", line 101, in get_installed_packages
    dc = debian_copyright.parse_copyright_file(copyright_location)
  File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/packagedcode/debian_copyright.py", line 198, in parse_copyright_file
    dc = StructuredCopyrightProcessor.from_file(
  File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/packagedcode/debian_copyright.py", line 453, in from_file
    dc.detect_license()
  File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/packagedcode/debian_copyright.py", line 678, in detect_license
    debian_licensing = DebianLicensing.from_license_paragraphs(
  File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/packagedcode/debian_copyright.py", line 934, in from_license_paragraphs
    result = DebianLicensing.parse_paras_with_license_text(
  File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/packagedcode/debian_copyright.py", line 1060, in parse_paras_with_license_text
    if not have_consistent_licenses_with_match(
  File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/packagedcode/debian_copyright.py", line 1728, in have_consistent_licenses_with_match
    if not reference_match.same_licensing(match):
  File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/licensedcode/match.py", line 346, in same_licensing
    return self.rule.same_licensing(other.rule)
  File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/licensedcode/models.py", line 1546, in same_licensing
    return self.licensing.is_equivalent(
  File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/license_expression/__init__.py", line 301, in is_equivalent
    ex2 = self._parse_and_simplify(expression2, **kwargs)
  File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/license_expression/__init__.py", line 326, in _parse_and_simplify
    return expression.simplify()
  File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/boolean/boolean.py", line 1281, in simplify
    if self.iscanonical:
```

**Comment by JonoYang** [comment]
Skipping the license detection part allows the docker pipeline to complete, but we get a lot of errors:

![image](https://user-images.githubusercontent.com/6044800/167973256-8f2bcf43-136e-4e76-8d46-44592a5aac9e.png)

This error shows up for the codebase resource created for the binaries in ``/usr/bin/``:
```
ERROR: for scanner: licenses: ERROR: Unknown error: Traceback (most recent call last): File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/scancode/interrupt.py", line 91, in interruptible return NO_ERROR, func(*(args or ()), **(kwargs or {})) File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/scancode/api.py", line 176, in get_licenses matches = idx.match( File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/licensedcode/index.py", line 925, in match return self.match_query( File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/licensedcode/index.py", line 996, in match_query matched = matcher( File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/licensedcode/index.py", line 668, in get_exact_matches matches, _discarded = match.refine_matches( File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/licensedcode/match.py", line 2596, in refine_matches matches, discarded = filter_invalid_matches_to_single_word_gibberish(matches) File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/licensedcode/match.py", line 1769, in filter_invalid_matches_to_single_word_gibberish rule_text = rule.text().strip() File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/licensedcode/models.py", line 1656, in text raise InvalidRule( licensedcode.models.InvalidRule: Inconsistent rule text for: gpl-3.0-plus_28.RULE file:///home/pombreda/w421/scancode-toolkit-licenses/src/licensedcode/data/rules/gpl-3.0-plus_28.RULE
--

[ERROR: for scanner: licenses: ERROR: Unknown error: Traceback (most recent call last): File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/scancode/interrupt.py", line 91, in interruptible return NO_ERROR, func(*(args or ()), **(kwargs or {})) File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/scancode/api.py", line 176, in get_licenses matches = idx.match( File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/licensedcode/index.py", line 925, in match return self.match_query( File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/licensedcode/index.py", line 996, in match_query matched = matcher( File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/licensedcode/index.py", line 668, in get_exact_matches matches, _discarded = match.refine_matches( File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/licensedcode/match.py", line 2596, in refine_matches matches, discarded = filter_invalid_matches_to_single_word_gibberish(matches) File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/licensedcode/match.py", line 1769, in filter_invalid_matches_to_single_word_gibberish rule_text = rule.text().strip() File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/licensedcode/models.py", line 1656, in text raise InvalidRule( licensedcode.models.InvalidRule: Inconsistent rule text for: gpl-3.0-plus_28.RULE file:///home/pombreda/w421/scancode-toolkit-licenses/src/licensedcode/data/rules/gpl-3.0-plus_28.RULE](http://127.0.0.1:8001/project/d80e10c3-e811-4d23-8e5c-f24c945f0e99/errors/?message=ERROR:%20for%20scanner:%20licenses:ERROR:%20Unknown%20error:Traceback%20(most%20recent%20call%20last):%20%20File%20%22/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/scancode/interrupt.py%22,%20line%2091,%20in%20interruptible%20%20%20%20return%20NO_ERROR,%20func(*(args%20or%20()),%20**(kwargs%20or%20{}))%20%20File%20%22/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/scancode/api.py%22,%20line%20176,%20in%20get_licenses%20%20%20%20matches%20=%20idx.match(%20%20File%20%22/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/licensedcode/index.py%22,%20line%20925,%20in%20match%20%20%20%20return%20self.match_query(%20%20File%20%22/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/licensedcode/index.py%22,%20line%20996,%20in%20match_query%20%20%20%20matched%20=%20matcher(%20%20File%20%22/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/licensedcode/index.py%22,%20line%20668,%20in%20get_exact_matches%20%20%20%20matches,%20_discarded%20=%20match.refine_matches(%20%20File%20%22/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/licensedcode/match.py%22,%20line%202596,%20in%20refine_matches%20%20%20%20matches,%20discarded%20=%20filter_invalid_matches_to_single_word_gibberish(matches)%20%20File%20%22/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/licensedcode/match.py%22,%20line%201769,%20in%20filter_invalid_matches_to_single_word_gibberish%20%20%20%20rule_text%20=%20rule.text().strip()%20%20File%20%22/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/licensedcode/models.py%22,%20line%201656,%20in%20text%20%20%20%20raise%20InvalidRule(licensedcode.models.InvalidRule:%20Inconsistent%20rule%20text%20for:%20gpl-3.0-plus_28.RULEfile:///home/pombreda/w421/scancode-toolkit-licenses/src/licensedcode/data/rules/gpl-3.0-plus_28.RULE)
```

This error shows up on copyright files from ``/usr/share/doc/``:
```
[ERROR: for scanner: licenses: ERROR: Unknown error: Traceback (most recent call last): File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/scancode/interrupt.py", line 91, in interruptible return NO_ERROR, func(*(args or ()), **(kwargs or {})) File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/scancode/api.py", line 192, in get_licenses _licenses_data_from_match( File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/scancode/api.py", line 240, in _licenses_data_from_match for license_key in match.rule.license_keys(): File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/licensedcode/models.py", line 1536, in license_keys return self.licensing.license_keys( File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/license_expression/__init__.py", line 411, in license_keys symbols = self.license_symbols( File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/license_expression/__init__.py", line 356, in license_symbols symbols = (s for s in expression.get_literals() if isinstance(s, BaseSymbol)) File "/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/boolean/boolean.py", line 674, in get_literals if self.isliteral: AttributeError: 'AND' object has no attribute 'isliteral'](http://127.0.0.1:8001/project/d80e10c3-e811-4d23-8e5c-f24c945f0e99/errors/?message=ERROR:%20for%20scanner:%20licenses:ERROR:%20Unknown%20error:Traceback%20(most%20recent%20call%20last):%20%20File%20%22/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/scancode/interrupt.py%22,%20line%2091,%20in%20interruptible%20%20%20%20return%20NO_ERROR,%20func(*(args%20or%20()),%20**(kwargs%20or%20{}))%20%20File%20%22/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/scancode/api.py%22,%20line%20192,%20in%20get_licenses%20%20%20%20_licenses_data_from_match(%20%20File%20%22/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/scancode/api.py%22,%20line%20240,%20in%20_licenses_data_from_match%20%20%20%20for%20license_key%20in%20match.rule.license_keys():%20%20File%20%22/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/licensedcode/models.py%22,%20line%201536,%20in%20license_keys%20%20%20%20return%20self.licensing.license_keys(%20%20File%20%22/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/license_expression/__init__.py%22,%20line%20411,%20in%20license_keys%20%20%20%20symbols%20=%20self.license_symbols(%20%20File%20%22/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/license_expression/__init__.py%22,%20line%20356,%20in%20license_symbols%20%20%20%20symbols%20=%20(s%20for%20s%20in%20expression.get_literals()%20if%20isinstance(s,%20BaseSymbol))%20%20File%20%22/home/jono/nexb/src/scancode.io/lib/python3.9/site-packages/boolean/boolean.py%22,%20line%20674,%20in%20get_literals%20%20%20%20if%20self.isliteral:AttributeError:%20%27AND%27%20object%20has%20no%20attribute%20%27isliteral%27)
```

**Comment by JonoYang** [comment]
Running ``scancode --reindex-licenses`` while in the scancode.io virtual environment seemed to have resolved the license errors, leaving the DiscoveredPackage errors where no version is provided when making a package.
