### ISSUE TITLE
Support any license key  in `build_spdx_license_expression`

### ISSUE THREAD

**Issue by tdruez** [nexB/scancode.io#753]
```
>>> from licensedcode.cache import build_spdx_license_expression
>>> build_spdx_license_expression("aaaa")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "python3.10/site-packages/licensedcode/cache.py", line 513, in build_spdx_license_expression
    validate_spdx_license_keys(license_expression=license_expression, licensing=licensing)
  File "python3.10/site-packages/licensedcode/cache.py", line 552, in validate_spdx_license_keys
    raise InvalidLicenseKeyError(messages)
licensedcode.cache.InvalidLicenseKeyError: ['License key: aaaa is not a valid license key from LicenseDB', 'License key: aaaa is not a valid license key from LicenseDB']
```

**Comment by tdruez** [comment]
Related to https://github.com/nexB/scancode.io/issues/749
